// quemSouEuDB.js — Quem Sou Eu? item database
// Structure: { nome, tags[], dif: 'facil'|'medio'|'dificil' }
// Tags: mz, global, cantor, atleta, ator, lider, influencer, personagem, animal, comida, marca, anime, biblia, objeto, lugar

export const QUEM_SOU_EU_DB = [

  // ── MZ MÚSICOS ───────────────────────────────────────────
  { nome: "Wazimbo",               tags: ["mz","cantor"],              dif: "medio"  },
  { nome: "Stewart Sukuma",        tags: ["mz","cantor"],              dif: "medio"  },
  { nome: "Mingas",                tags: ["mz","cantor"],              dif: "medio"  },
  { nome: "Neyma",                 tags: ["mz","cantor"],              dif: "facil"  },
  { nome: "Lizha James",           tags: ["mz","cantor"],              dif: "facil"  },
  { nome: "Marllen",               tags: ["mz","cantor"],              dif: "medio"  },
  { nome: "Lourena Nhate",         tags: ["mz","cantor"],              dif: "medio"  },
  { nome: "Ziqo",                  tags: ["mz","cantor"],              dif: "facil"  },
  { nome: "Mr. Bow",               tags: ["mz","cantor"],              dif: "facil"  },
  { nome: "MC Roger",              tags: ["mz","cantor"],              dif: "facil"  },
  { nome: "Azagaia",               tags: ["mz","cantor"],              dif: "facil"  },
  { nome: "Dama do Bling",         tags: ["mz","cantor"],              dif: "medio"  },
  { nome: "Tamyris Moiane",        tags: ["mz","cantor"],              dif: "medio"  },
  { nome: "Bander",                tags: ["mz","cantor"],              dif: "medio"  },
  { nome: "Laylizzy",              tags: ["mz","cantor"],              dif: "facil"  },
  { nome: "Hot Blaze",             tags: ["mz","cantor"],              dif: "medio"  },
  { nome: "Twenty Fingers",        tags: ["mz","cantor"],              dif: "facil"  },
  { nome: "Percella",              tags: ["mz","cantor"],              dif: "medio"  },
  { nome: "Justino Ubakka",        tags: ["mz","cantor"],              dif: "medio"  },
  { nome: "Stefânia Leonel",       tags: ["mz","cantor"],              dif: "medio"  },
  { nome: "Dygo Boy",              tags: ["mz","cantor"],              dif: "medio"  },
  { nome: "Edu All Talents",       tags: ["mz","cantor"],              dif: "medio"  },
  { nome: "Djimetta",              tags: ["mz","cantor"],              dif: "medio"  },
  { nome: "Feliciano dos Santos",  tags: ["mz","cantor"],              dif: "dificil"},
  { nome: "Ghorwane",              tags: ["mz","cantor"],              dif: "dificil"},
  { nome: "Iveth",                 tags: ["mz","cantor"],              dif: "dificil"},
  { nome: "Yadah",                 tags: ["mz","cantor"],              dif: "dificil"},
  { nome: "Jay Argh",              tags: ["mz","cantor"],              dif: "dificil"},
  { nome: "Valdemiro José",        tags: ["mz","cantor"],              dif: "dificil"},
  { nome: "Hernâni da Silva",      tags: ["mz","cantor"],              dif: "dificil"},
  { nome: "Bangla 10",             tags: ["mz","cantor"],              dif: "dificil"},
  { nome: "Kiba the Seven",        tags: ["mz","cantor"],              dif: "dificil"},
  { nome: "Kamane Kamas",          tags: ["mz","cantor"],              dif: "dificil"},
  { nome: "Doppaz",                tags: ["mz","cantor"],              dif: "dificil"},
  { nome: "Puto Aires",            tags: ["mz","cantor"],              dif: "dificil"},

  // ── MZ LÍDERES & PERSONALIDADES ─────────────────────────
  { nome: "Samora Machel",         tags: ["mz","lider"],              dif: "facil"  },
  { nome: "Eduardo Mondlane",      tags: ["mz","lider"],              dif: "facil"  },
  { nome: "Joaquim Chissano",      tags: ["mz","lider"],              dif: "medio"  },
  { nome: "Armando Guebuza",       tags: ["mz","lider"],              dif: "medio"  },
  { nome: "Filipe Nyusi",          tags: ["mz","lider"],              dif: "facil"  },
  { nome: "Graça Machel",          tags: ["mz","lider"],              dif: "medio"  },
  { nome: "Venâncio Mondlane",     tags: ["mz","lider"],              dif: "facil"  },
  { nome: "Daniel Chapo",          tags: ["mz","lider"],              dif: "medio"  },
  { nome: "Josina Machel",         tags: ["mz","lider"],              dif: "dificil"},
  { nome: "Afonso Dhlakama",       tags: ["mz","lider"],              dif: "medio"  },
  { nome: "Daviz Simango",         tags: ["mz","lider"],              dif: "medio"  },
  { nome: "Mia Couto",             tags: ["mz","lider"],              dif: "medio"  },
  { nome: "Paulina Chiziane",      tags: ["mz","lider"],              dif: "dificil"},
  { nome: "José Craveirinha",      tags: ["mz","lider"],              dif: "dificil"},
  { nome: "Malangatana",           tags: ["mz","lider"],              dif: "dificil"},
  { nome: "Gungunhana",            tags: ["mz","lider"],              dif: "medio"  },

  // ── MZ ATLETAS ───────────────────────────────────────────
  { nome: "Eusébio",               tags: ["mz","atleta"],             dif: "facil"  },
  { nome: "Mário Coluna",          tags: ["mz","atleta"],             dif: "medio"  },
  { nome: "Lurdes Mutola",         tags: ["mz","atleta"],             dif: "medio"  },
  { nome: "Tico-Tico",             tags: ["mz","atleta"],             dif: "medio"  },
  { nome: "Genito Bila",           tags: ["mz","atleta"],             dif: "dificil"},
  { nome: "Dominguês",             tags: ["mz","atleta"],             dif: "dificil"},
  { nome: "Chiquinho Conde",       tags: ["mz","atleta"],             dif: "dificil"},

  // ── MZ INFLUENCERS ───────────────────────────────────────
  { nome: "Guyzelh Ramos",         tags: ["mz","influencer"],         dif: "facil"  },
  { nome: "Maxh 258",              tags: ["mz","influencer"],         dif: "medio"  },
  { nome: "Victor Renér",          tags: ["mz","influencer"],         dif: "medio"  },
  { nome: "Igor Idelson",          tags: ["mz","influencer"],         dif: "dificil"},
  { nome: "Noslen Araújo",         tags: ["mz","influencer"],         dif: "dificil"},
  { nome: "Maira Santos",          tags: ["mz","influencer"],         dif: "dificil"},
  { nome: "Stélio Leonel",         tags: ["mz","influencer"],         dif: "dificil"},
  { nome: "Cardo Podcast",         tags: ["mz","influencer"],         dif: "medio"  },

  // ── MZ COMIDA ────────────────────────────────────────────
  { nome: "Matapa",                tags: ["mz","comida"],             dif: "facil"  },
  { nome: "Xima",                  tags: ["mz","comida"],             dif: "facil"  },
  { nome: "Chamussas",             tags: ["mz","comida"],             dif: "facil"  },
  { nome: "Badjias",               tags: ["mz","comida"],             dif: "facil"  },
  { nome: "Pão com Badjia",        tags: ["mz","comida"],             dif: "facil"  },
  { nome: "Galinha à Zambeziana",  tags: ["mz","comida"],             dif: "medio"  },
  { nome: "Frango à Cafreal",      tags: ["mz","comida"],             dif: "medio"  },
  { nome: "Caril de Amendoim",     tags: ["mz","comida"],             dif: "medio"  },
  { nome: "Piri-Piri",             tags: ["mz","comida"],             dif: "facil"  },
  { nome: "Lagosta de Moçambique", tags: ["mz","comida"],             dif: "medio"  },
  { nome: "Maheu",                 tags: ["mz","comida"],             dif: "medio"  },
  { nome: "Caju",                  tags: ["mz","comida"],             dif: "facil"  },
  { nome: "2M",                    tags: ["mz","comida","marca"],     dif: "facil"  },
  { nome: "Laurentina",            tags: ["mz","comida","marca"],     dif: "facil"  },
  { nome: "Bolo Polana",           tags: ["mz","comida"],             dif: "medio"  },

  // ── MZ MARCAS ────────────────────────────────────────────
  { nome: "Vodacom Moçambique",    tags: ["mz","marca"],              dif: "facil"  },
  { nome: "Tmcel",                 tags: ["mz","marca"],              dif: "facil"  },
  { nome: "Movitel",               tags: ["mz","marca"],              dif: "facil"  },
  { nome: "BCI",                   tags: ["mz","marca"],              dif: "medio"  },
  { nome: "Millennium Bim",        tags: ["mz","marca"],              dif: "facil"  },
  { nome: "Standard Bank MZ",      tags: ["mz","marca"],              dif: "medio"  },
  { nome: "STV",                   tags: ["mz","marca"],              dif: "facil"  },
  { nome: "TVM",                   tags: ["mz","marca"],              dif: "facil"  },
  { nome: "Yango",                 tags: ["mz","marca"],              dif: "facil"  },
  { nome: "Moza Bank",             tags: ["mz","marca"],              dif: "medio"  },
  { nome: "Txilar",                tags: ["mz","marca"],              dif: "medio"  },

  // ── MZ OBJETOS / CONCEITOS ───────────────────────────────
  { nome: "Capulana",              tags: ["mz","objeto"],             dif: "facil"  },
  { nome: "Chapa",                 tags: ["mz","objeto"],             dif: "facil"  },
  { nome: "Txopela",               tags: ["mz","objeto"],             dif: "facil"  },
  { nome: "Lobolo",                tags: ["mz","objeto"],             dif: "facil"  },
  { nome: "Xitique",               tags: ["mz","objeto"],             dif: "medio"  },
  { nome: "Timbila",               tags: ["mz","objeto"],             dif: "medio"  },
  { nome: "Mbira",                 tags: ["mz","objeto"],             dif: "medio"  },
  { nome: "Marrabenta",            tags: ["mz","objeto"],             dif: "medio"  },
  { nome: "Metical",               tags: ["mz","objeto"],             dif: "facil"  },
  { nome: "Curandeiro",            tags: ["mz","objeto"],             dif: "facil"  },
  { nome: "Machamba",              tags: ["mz","objeto"],             dif: "medio"  },
  { nome: "Pilão",                 tags: ["mz","objeto"],             dif: "medio"  },
  { nome: "Catana",                tags: ["mz","objeto"],             dif: "medio"  },

  // ── MZ LUGARES ───────────────────────────────────────────
  { nome: "Ilha de Moçambique",    tags: ["mz","lugar"],              dif: "facil"  },
  { nome: "Gorongosa",             tags: ["mz","lugar"],              dif: "facil"  },
  { nome: "Cahora Bassa",          tags: ["mz","lugar"],              dif: "facil"  },
  { nome: "Ponta do Ouro",         tags: ["mz","lugar"],              dif: "medio"  },
  { nome: "Vilankulo",             tags: ["mz","lugar"],              dif: "medio"  },
  { nome: "Pemba",                 tags: ["mz","lugar"],              dif: "medio"  },
  { nome: "Ilha do Bazaruto",      tags: ["mz","lugar"],              dif: "medio"  },
  { nome: "Tofo",                  tags: ["mz","lugar"],              dif: "medio"  },
  { nome: "Bilene",                tags: ["mz","lugar"],              dif: "medio"  },
  { nome: "Xai-Xai",              tags: ["mz","lugar"],              dif: "facil"  },
  { nome: "Chimoio",               tags: ["mz","lugar"],              dif: "facil"  },
  { nome: "Quelimane",             tags: ["mz","lugar"],              dif: "facil"  },
  { nome: "Mafalala",              tags: ["mz","lugar"],              dif: "medio"  },
  { nome: "Maputo",                tags: ["mz","lugar"],              dif: "facil"  },
  { nome: "Beira",                 tags: ["mz","lugar"],              dif: "facil"  },
  { nome: "Nampula",               tags: ["mz","lugar"],              dif: "facil"  },

  // ── MZ ANIMAIS ───────────────────────────────────────────
  { nome: "Mamba",                 tags: ["mz","animal"],             dif: "facil"  },
  { nome: "Hipopótamo",            tags: ["mz","animal"],             dif: "facil"  },
  { nome: "Tubarão-Baleia",        tags: ["mz","animal"],             dif: "medio"  },
  { nome: "Flamingo",              tags: ["mz","animal"],             dif: "facil"  },
  { nome: "Búfalo",                tags: ["mz","animal"],             dif: "medio"  },
  { nome: "Camaleão",              tags: ["mz","animal"],             dif: "facil"  },

  // ── GLOBAL MÚSICOS ───────────────────────────────────────
  { nome: "Michael Jackson",       tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Elvis Presley",         tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Madonna",               tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Bob Marley",            tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Freddie Mercury",       tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Beyoncé",               tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Rihanna",               tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Taylor Swift",          tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Drake",                 tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Eminem",                tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Jay-Z",                 tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Kanye West",            tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Adele",                 tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Lady Gaga",             tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Bruno Mars",            tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Justin Bieber",         tags: ["global","cantor"],         dif: "facil"  },
  { nome: "The Weeknd",            tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Ed Sheeran",            tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Billie Eilish",         tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Shakira",               tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Nicki Minaj",           tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Cardi B",               tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Post Malone",           tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Snoop Dogg",            tags: ["global","cantor"],         dif: "facil"  },
  { nome: "50 Cent",               tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Tupac",                 tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Bob Dylan",             tags: ["global","cantor"],         dif: "medio"  },
  { nome: "Elton John",            tags: ["global","cantor"],         dif: "facil"  },
  { nome: "David Bowie",           tags: ["global","cantor"],         dif: "medio"  },
  { nome: "Amy Winehouse",         tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Britney Spears",        tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Chris Brown",           tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Dua Lipa",              tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Bad Bunny",             tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Ariana Grande",         tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Kendrick Lamar",        tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Travis Scott",          tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Daddy Yankee",          tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Whitney Houston",       tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Aretha Franklin",       tags: ["global","cantor"],         dif: "medio"  },
  { nome: "Usher",                 tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Burna Boy",             tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Wizkid",                tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Davido",                tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Diamond Platnumz",      tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Harmonize",             tags: ["global","cantor"],         dif: "medio"  },
  { nome: "Fally Ipupa",           tags: ["global","cantor"],         dif: "medio"  },
  { nome: "C4 Pedro",              tags: ["global","cantor"],         dif: "medio"  },
  { nome: "Anselmo Ralph",         tags: ["global","cantor"],         dif: "medio"  },
  { nome: "Matias Damásio",        tags: ["global","cantor"],         dif: "medio"  },
  { nome: "Calema",                tags: ["global","cantor"],         dif: "medio"  },
  { nome: "J Balvin",              tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Karol G",               tags: ["global","cantor"],         dif: "facil"  },
  { nome: "BTS",                   tags: ["global","cantor"],         dif: "facil"  },
  { nome: "BLACKPINK",             tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Daft Punk",             tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Avicii",                tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Queen",                 tags: ["global","cantor"],         dif: "facil"  },
  { nome: "The Beatles",           tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Nirvana",               tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Metallica",             tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Linkin Park",           tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Coldplay",              tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Maroon 5",              tags: ["global","cantor"],         dif: "facil"  },
  { nome: "One Direction",         tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Spice Girls",           tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Backstreet Boys",       tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Anitta",                tags: ["global","cantor"],         dif: "facil"  },
  { nome: "Marília Mendonça",      tags: ["global","cantor"],         dif: "facil"  },

  // ── GLOBAL ATLETAS ───────────────────────────────────────
  { nome: "Cristiano Ronaldo",     tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Lionel Messi",          tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Neymar",                tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Kylian Mbappé",         tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Erling Haaland",        tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Pelé",                  tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Maradona",              tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Ronaldinho",            tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Zinedine Zidane",       tags: ["global","atleta"],         dif: "facil"  },
  { nome: "David Beckham",         tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Ronaldo Fenómeno",      tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Mohamed Salah",         tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Vinícius Júnior",       tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Jude Bellingham",       tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Michael Jordan",        tags: ["global","atleta"],         dif: "facil"  },
  { nome: "LeBron James",          tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Kobe Bryant",           tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Stephen Curry",         tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Usain Bolt",            tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Muhammad Ali",          tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Mike Tyson",            tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Floyd Mayweather",      tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Conor McGregor",        tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Serena Williams",       tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Roger Federer",         tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Rafael Nadal",          tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Novak Djokovic",        tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Tiger Woods",           tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Lewis Hamilton",        tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Ayrton Senna",          tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Max Verstappen",        tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Simone Biles",          tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Thierry Henry",         tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Zlatan Ibrahimović",    tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Didier Drogba",         tags: ["global","atleta"],         dif: "medio"  },
  { nome: "Samuel Eto'o",          tags: ["global","atleta"],         dif: "medio"  },
  { nome: "Sadio Mané",            tags: ["global","atleta"],         dif: "facil"  },
  { nome: "The Rock",              tags: ["global","atleta","ator"],  dif: "facil"  },
  { nome: "John Cena",             tags: ["global","atleta","ator"],  dif: "facil"  },
  { nome: "Lamine Yamal",          tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Tom Brady",             tags: ["global","atleta"],         dif: "facil"  },
  { nome: "Khabib Nurmagomedov",   tags: ["global","atleta"],         dif: "medio"  },
  { nome: "Israel Adesanya",       tags: ["global","atleta"],         dif: "medio"  },

  // ── GLOBAL ATORES ────────────────────────────────────────
  { nome: "Leonardo DiCaprio",     tags: ["global","ator"],           dif: "facil"  },
  { nome: "Tom Hanks",             tags: ["global","ator"],           dif: "facil"  },
  { nome: "Brad Pitt",             tags: ["global","ator"],           dif: "facil"  },
  { nome: "Will Smith",            tags: ["global","ator"],           dif: "facil"  },
  { nome: "Ryan Reynolds",         tags: ["global","ator"],           dif: "facil"  },
  { nome: "Keanu Reeves",          tags: ["global","ator"],           dif: "facil"  },
  { nome: "Tom Cruise",            tags: ["global","ator"],           dif: "facil"  },
  { nome: "Robert Downey Jr.",     tags: ["global","ator"],           dif: "facil"  },
  { nome: "Johnny Depp",           tags: ["global","ator"],           dif: "facil"  },
  { nome: "Morgan Freeman",        tags: ["global","ator"],           dif: "facil"  },
  { nome: "Denzel Washington",     tags: ["global","ator"],           dif: "facil"  },
  { nome: "Angelina Jolie",        tags: ["global","ator"],           dif: "facil"  },
  { nome: "Scarlett Johansson",    tags: ["global","ator"],           dif: "facil"  },
  { nome: "Margot Robbie",         tags: ["global","ator"],           dif: "facil"  },
  { nome: "Zendaya",               tags: ["global","ator"],           dif: "facil"  },
  { nome: "Emma Watson",           tags: ["global","ator"],           dif: "facil"  },
  { nome: "Gal Gadot",             tags: ["global","ator"],           dif: "facil"  },
  { nome: "Jim Carrey",            tags: ["global","ator"],           dif: "facil"  },
  { nome: "Kevin Hart",            tags: ["global","ator"],           dif: "facil"  },
  { nome: "Adam Sandler",          tags: ["global","ator"],           dif: "facil"  },
  { nome: "Arnold Schwarzenegger", tags: ["global","ator"],           dif: "facil"  },
  { nome: "Sylvester Stallone",    tags: ["global","ator"],           dif: "facil"  },
  { nome: "Jackie Chan",           tags: ["global","ator"],           dif: "facil"  },
  { nome: "Bruce Lee",             tags: ["global","ator"],           dif: "facil"  },
  { nome: "Marilyn Monroe",        tags: ["global","ator"],           dif: "facil"  },
  { nome: "Audrey Hepburn",        tags: ["global","ator"],           dif: "medio"  },
  { nome: "Charles Chaplin",       tags: ["global","ator"],           dif: "facil"  },
  { nome: "Jennifer Lawrence",     tags: ["global","ator"],           dif: "facil"  },

  // ── GLOBAL INFLUENCERS ───────────────────────────────────
  { nome: "Kim Kardashian",        tags: ["global","influencer"],     dif: "facil"  },
  { nome: "Kylie Jenner",          tags: ["global","influencer"],     dif: "facil"  },
  { nome: "MrBeast",               tags: ["global","influencer"],     dif: "facil"  },
  { nome: "PewDiePie",             tags: ["global","influencer"],     dif: "facil"  },
  { nome: "Oprah Winfrey",         tags: ["global","influencer"],     dif: "facil"  },
  { nome: "Gordon Ramsay",         tags: ["global","influencer"],     dif: "facil"  },
  { nome: "KSI",                   tags: ["global","influencer"],     dif: "facil"  },
  { nome: "Logan Paul",            tags: ["global","influencer"],     dif: "facil"  },
  { nome: "IShowSpeed",            tags: ["global","influencer"],     dif: "facil"  },
  { nome: "Khaby Lame",            tags: ["global","influencer"],     dif: "facil"  },

  // ── GLOBAL LÍDERES ───────────────────────────────────────
  { nome: "Nelson Mandela",        tags: ["global","lider"],          dif: "facil"  },
  { nome: "Barack Obama",          tags: ["global","lider"],          dif: "facil"  },
  { nome: "Donald Trump",          tags: ["global","lider"],          dif: "facil"  },
  { nome: "Vladimir Putin",        tags: ["global","lider"],          dif: "facil"  },
  { nome: "Papa Francisco",        tags: ["global","lider"],          dif: "facil"  },
  { nome: "Mahatma Gandhi",        tags: ["global","lider"],          dif: "facil"  },
  { nome: "Martin Luther King",    tags: ["global","lider"],          dif: "facil"  },
  { nome: "Abraham Lincoln",       tags: ["global","lider"],          dif: "facil"  },
  { nome: "Winston Churchill",     tags: ["global","lider"],          dif: "medio"  },
  { nome: "Napoleão Bonaparte",    tags: ["global","lider"],          dif: "facil"  },
  { nome: "Cleópatra",             tags: ["global","lider"],          dif: "facil"  },
  { nome: "Júlio César",           tags: ["global","lider"],          dif: "facil"  },
  { nome: "Alexandre o Grande",    tags: ["global","lider"],          dif: "facil"  },
  { nome: "Adolf Hitler",          tags: ["global","lider"],          dif: "facil"  },
  { nome: "Albert Einstein",       tags: ["global","lider"],          dif: "facil"  },
  { nome: "Nikola Tesla",          tags: ["global","lider"],          dif: "facil"  },
  { nome: "Leonardo da Vinci",     tags: ["global","lider"],          dif: "facil"  },
  { nome: "Marie Curie",           tags: ["global","lider"],          dif: "facil"  },
  { nome: "Elon Musk",             tags: ["global","lider"],          dif: "facil"  },
  { nome: "Bill Gates",            tags: ["global","lider"],          dif: "facil"  },
  { nome: "Steve Jobs",            tags: ["global","lider"],          dif: "facil"  },
  { nome: "Mark Zuckerberg",       tags: ["global","lider"],          dif: "facil"  },
  { nome: "Jeff Bezos",            tags: ["global","lider"],          dif: "facil"  },
  { nome: "Princesa Diana",        tags: ["global","lider"],          dif: "facil"  },
  { nome: "Rainha Elizabeth II",   tags: ["global","lider"],          dif: "facil"  },

  // ── PERSONAGENS FICTÍCIOS ────────────────────────────────
  { nome: "Batman",                tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Superman",              tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Spider-Man",            tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Hulk",                  tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Thor",                  tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Homem de Ferro",        tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Capitão América",       tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Deadpool",              tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Wolverine",             tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Thanos",                tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Joker",                 tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Darth Vader",           tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Harley Quinn",          tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Venom",                 tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Harry Potter",          tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Hermione Granger",      tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Voldemort",             tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Gandalf",               tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Sherlock Holmes",       tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Mickey Mouse",          tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Simba",                 tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Elsa",                  tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Woody",                 tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Buzz Lightyear",        tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Nemo",                  tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Shrek",                 tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Pikachu",               tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Mario",                 tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Sonic",                 tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Homer Simpson",         tags: ["global","personagem"],     dif: "facil"  },
  { nome: "SpongeBob",             tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Bugs Bunny",            tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Scooby-Doo",            tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Baby Yoda",             tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Walter White",          tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Jack Sparrow",          tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Drácula",               tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Frankenstein",          tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Peter Pan",             tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Pinóquio",              tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Gru",                   tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Stitch",                tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Moana",                 tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Rapunzel",              tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Rick Sanchez",          tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Tommy Shelby",          tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Jon Snow",              tags: ["global","personagem"],     dif: "facil"  },
  { nome: "Daenerys Targaryen",    tags: ["global","personagem"],     dif: "facil"  },

  // ── GLOBAL ANIMAIS ───────────────────────────────────────
  { nome: "Leão",                  tags: ["global","animal"],         dif: "facil"  },
  { nome: "Elefante",              tags: ["global","animal"],         dif: "facil"  },
  { nome: "Tubarão",               tags: ["global","animal"],         dif: "facil"  },
  { nome: "Golfinho",              tags: ["global","animal"],         dif: "facil"  },
  { nome: "Gorila",                tags: ["global","animal"],         dif: "facil"  },
  { nome: "Cobra",                 tags: ["global","animal"],         dif: "facil"  },
  { nome: "Águia",                 tags: ["global","animal"],         dif: "facil"  },
  { nome: "Urso",                  tags: ["global","animal"],         dif: "facil"  },
  { nome: "Lobo",                  tags: ["global","animal"],         dif: "facil"  },
  { nome: "Tigre",                 tags: ["global","animal"],         dif: "facil"  },
  { nome: "Pinguim",               tags: ["global","animal"],         dif: "facil"  },
  { nome: "Girafa",                tags: ["global","animal"],         dif: "facil"  },
  { nome: "Crocodilo",             tags: ["global","animal"],         dif: "facil"  },
  { nome: "Panda",                 tags: ["global","animal"],         dif: "facil"  },
  { nome: "Canguru",               tags: ["global","animal"],         dif: "facil"  },
  { nome: "Polvo",                 tags: ["global","animal"],         dif: "facil"  },
  { nome: "Baleia",                tags: ["global","animal"],         dif: "facil"  },
  { nome: "Koala",                 tags: ["global","animal"],         dif: "facil"  },
  { nome: "Tartaruga",             tags: ["global","animal"],         dif: "facil"  },
  { nome: "Papagaio",              tags: ["global","animal"],         dif: "facil"  },
  { nome: "T-Rex",                 tags: ["global","animal"],         dif: "facil"  },
  { nome: "Unicórnio",             tags: ["global","animal"],         dif: "facil"  },
  { nome: "Dragão",                tags: ["global","animal"],         dif: "facil"  },
  { nome: "Pato Donald",           tags: ["global","animal","personagem"], dif: "facil" },
  { nome: "Tom e Jerry",           tags: ["global","animal","personagem"], dif: "facil" },
  { nome: "Simba",                 tags: ["global","animal","personagem"], dif: "facil" },
  { nome: "Dumbo",                 tags: ["global","animal","personagem"], dif: "facil" },
  { nome: "Bambi",                 tags: ["global","animal","personagem"], dif: "facil" },
  { nome: "Coelho",                tags: ["global","animal"],         dif: "facil"  },
  { nome: "Cavalo",                tags: ["global","animal"],         dif: "facil"  },
  { nome: "Vaca",                  tags: ["global","animal"],         dif: "facil"  },
  { nome: "Porco",                 tags: ["global","animal"],         dif: "facil"  },

  // ── GLOBAL COMIDA ────────────────────────────────────────
  { nome: "Pizza",                 tags: ["global","comida"],         dif: "facil"  },
  { nome: "Hambúrguer",            tags: ["global","comida"],         dif: "facil"  },
  { nome: "Sushi",                 tags: ["global","comida"],         dif: "facil"  },
  { nome: "Chocolate",             tags: ["global","comida"],         dif: "facil"  },
  { nome: "Coca-Cola",             tags: ["global","comida","marca"], dif: "facil"  },
  { nome: "Gelado",                tags: ["global","comida"],         dif: "facil"  },
  { nome: "Café",                  tags: ["global","comida"],         dif: "facil"  },
  { nome: "Cerveja",               tags: ["global","comida"],         dif: "facil"  },
  { nome: "Taco",                  tags: ["global","comida"],         dif: "facil"  },
  { nome: "Croissant",             tags: ["global","comida"],         dif: "facil"  },
  { nome: "Bolo",                  tags: ["global","comida"],         dif: "facil"  },
  { nome: "Pipoca",                tags: ["global","comida"],         dif: "facil"  },
  { nome: "Banana",                tags: ["global","comida"],         dif: "facil"  },
  { nome: "Morango",               tags: ["global","comida"],         dif: "facil"  },
  { nome: "Donut",                 tags: ["global","comida"],         dif: "facil"  },

  // ── GLOBAL MARCAS ────────────────────────────────────────
  { nome: "Nike",                  tags: ["global","marca"],          dif: "facil"  },
  { nome: "Ferrari",               tags: ["global","marca"],          dif: "facil"  },
  { nome: "McDonald's",            tags: ["global","marca"],          dif: "facil"  },
  { nome: "Apple",                 tags: ["global","marca"],          dif: "facil"  },
  { nome: "Google",                tags: ["global","marca"],          dif: "facil"  },
  { nome: "Netflix",               tags: ["global","marca"],          dif: "facil"  },
  { nome: "PlayStation",           tags: ["global","marca"],          dif: "facil"  },
  { nome: "Bitcoin",               tags: ["global","marca"],          dif: "facil"  },
  { nome: "Barbie",                tags: ["global","marca"],          dif: "facil"  },
  { nome: "LEGO",                  tags: ["global","marca"],          dif: "facil"  },
  { nome: "Adidas",                tags: ["global","marca"],          dif: "facil"  },
  { nome: "Mercedes",              tags: ["global","marca"],          dif: "facil"  },
  { nome: "WhatsApp",              tags: ["global","marca"],          dif: "facil"  },
  { nome: "Instagram",             tags: ["global","marca"],          dif: "facil"  },
  { nome: "TikTok",                tags: ["global","marca"],          dif: "facil"  },
  { nome: "YouTube",               tags: ["global","marca"],          dif: "facil"  },
  { nome: "Xbox",                  tags: ["global","marca"],          dif: "facil"  },
  { nome: "Red Bull",              tags: ["global","marca"],          dif: "facil"  },
  { nome: "Pepsi",                 tags: ["global","marca"],          dif: "facil"  },
  { nome: "Amazon",                tags: ["global","marca"],          dif: "facil"  },
  { nome: "Lamborghini",           tags: ["global","marca"],          dif: "facil"  },
  { nome: "Louis Vuitton",         tags: ["global","marca"],          dif: "medio"  },
  { nome: "Gucci",                 tags: ["global","marca"],          dif: "facil"  },
  { nome: "Samsung",               tags: ["global","marca"],          dif: "facil"  },

  // ── ANIME ────────────────────────────────────────────────
  { nome: "Goku",                  tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Vegeta",                tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Naruto",                tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Sasuke",                tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Luffy",                 tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Zoro",                  tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Sanji",                 tags: ["anime","personagem"],      dif: "medio"  },
  { nome: "Nami",                  tags: ["anime","personagem"],      dif: "medio"  },
  { nome: "Ichigo",                tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Eren Jaeger",           tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Mikasa",                tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Levi",                  tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Tanjiro",               tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Nezuko",                tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Deku",                  tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Bakugo",                tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Todoroki",              tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "All Might",             tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Gojo Satoru",           tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Yuji Itadori",          tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Sukuna",                tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Light Yagami",          tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "L",                     tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Edward Elric",          tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Killua",                tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Gon",                   tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Hisoka",                tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Saitama",               tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Kakashi",               tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Itachi",                tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Madara",                tags: ["anime","personagem"],      dif: "medio"  },
  { nome: "Frieza",                tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Sailor Moon",           tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Ash Ketchum",           tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Pikachu",               tags: ["anime","personagem"],      dif: "facil"  },
  { nome: "Dragon Ball Z",         tags: ["anime"],                   dif: "facil"  },
  { nome: "One Piece",             tags: ["anime"],                   dif: "facil"  },
  { nome: "Naruto Shippuden",      tags: ["anime"],                   dif: "facil"  },
  { nome: "Bleach",                tags: ["anime"],                   dif: "facil"  },
  { nome: "Attack on Titan",       tags: ["anime"],                   dif: "facil"  },
  { nome: "Demon Slayer",          tags: ["anime"],                   dif: "facil"  },
  { nome: "Jujutsu Kaisen",        tags: ["anime"],                   dif: "facil"  },
  { nome: "My Hero Academia",      tags: ["anime"],                   dif: "facil"  },
  { nome: "Death Note",            tags: ["anime"],                   dif: "facil"  },
  { nome: "Fullmetal Alchemist",   tags: ["anime"],                   dif: "facil"  },
  { nome: "Hunter x Hunter",       tags: ["anime"],                   dif: "facil"  },
  { nome: "One Punch Man",         tags: ["anime"],                   dif: "facil"  },
  { nome: "Fairy Tail",            tags: ["anime"],                   dif: "facil"  },
  { nome: "Sword Art Online",      tags: ["anime"],                   dif: "facil"  },
  { nome: "Cavaleiros do Zodíaco", tags: ["anime"],                   dif: "facil"  },
  { nome: "Yu-Gi-Oh!",             tags: ["anime"],                   dif: "facil"  },

  // ── BÍBLIA ───────────────────────────────────────────────
  { nome: "Adão",                  tags: ["biblia"],                  dif: "facil"  },
  { nome: "Eva",                   tags: ["biblia"],                  dif: "facil"  },
  { nome: "Noé",                   tags: ["biblia"],                  dif: "facil"  },
  { nome: "Abraão",                tags: ["biblia"],                  dif: "facil"  },
  { nome: "Moisés",                tags: ["biblia"],                  dif: "facil"  },
  { nome: "Davi",                  tags: ["biblia"],                  dif: "facil"  },
  { nome: "Golias",                tags: ["biblia"],                  dif: "facil"  },
  { nome: "Salomão",               tags: ["biblia"],                  dif: "facil"  },
  { nome: "Sansão",                tags: ["biblia"],                  dif: "facil"  },
  { nome: "Dalila",                tags: ["biblia"],                  dif: "facil"  },
  { nome: "Jonas",                 tags: ["biblia"],                  dif: "facil"  },
  { nome: "Daniel",                tags: ["biblia"],                  dif: "facil"  },
  { nome: "Ester",                 tags: ["biblia"],                  dif: "facil"  },
  { nome: "Jesus",                 tags: ["biblia"],                  dif: "facil"  },
  { nome: "Maria",                 tags: ["biblia"],                  dif: "facil"  },
  { nome: "Pedro",                 tags: ["biblia"],                  dif: "facil"  },
  { nome: "Paulo",                 tags: ["biblia"],                  dif: "facil"  },
  { nome: "João",                  tags: ["biblia"],                  dif: "facil"  },
  { nome: "Judas",                 tags: ["biblia"],                  dif: "facil"  },
  { nome: "Herodes",               tags: ["biblia"],                  dif: "facil"  },
  { nome: "Pilatos",               tags: ["biblia"],                  dif: "facil"  },
  { nome: "João Batista",          tags: ["biblia"],                  dif: "facil"  },
  { nome: "Elias",                 tags: ["biblia"],                  dif: "medio"  },
  { nome: "Josué",                 tags: ["biblia"],                  dif: "medio"  },
  { nome: "Samuel",                tags: ["biblia"],                  dif: "medio"  },
  { nome: "Saul",                  tags: ["biblia"],                  dif: "medio"  },
  { nome: "Rute",                  tags: ["biblia"],                  dif: "medio"  },
  { nome: "Ester",                 tags: ["biblia"],                  dif: "medio"  },
  { nome: "Isaías",                tags: ["biblia"],                  dif: "medio"  },
  { nome: "Jeremias",              tags: ["biblia"],                  dif: "medio"  },
  { nome: "Débora",                tags: ["biblia"],                  dif: "dificil"},
  { nome: "Gideão",                tags: ["biblia"],                  dif: "dificil"},
  { nome: "Maria Madalena",        tags: ["biblia"],                  dif: "medio"  },
  { nome: "Lázaro",                tags: ["biblia"],                  dif: "medio"  },
  { nome: "Génesis",               tags: ["biblia"],                  dif: "facil"  },
  { nome: "Êxodo",                 tags: ["biblia"],                  dif: "facil"  },
  { nome: "Salmos",                tags: ["biblia"],                  dif: "facil"  },
  { nome: "Provérbios",            tags: ["biblia"],                  dif: "facil"  },
  { nome: "Apocalipse",            tags: ["biblia"],                  dif: "facil"  },
  { nome: "Cantares",              tags: ["biblia"],                  dif: "medio"  },
  { nome: "Eclesiastes",           tags: ["biblia"],                  dif: "medio"  },
  { nome: "Job",                   tags: ["biblia"],                  dif: "medio"  },
  { nome: "Hebreus",               tags: ["biblia"],                  dif: "dificil"},
  { nome: "Romanos",               tags: ["biblia"],                  dif: "dificil"},
  { nome: "Coríntios",             tags: ["biblia"],                  dif: "dificil"},
];

export const CATEGORIAS = [
  { id: "mix",        nome: "Mix",         tag: null,         emoji: "🎲", bg: "linear-gradient(135deg,#7c5dfa,#5c4fd6)", shadow: "rgba(124,93,250,0.5)" },
  { id: "mz",         nome: "Moçambique",  tag: "mz",         emoji: "🇲🇿", bg: "linear-gradient(135deg,#16a34a,#15803d)", shadow: "rgba(22,163,74,0.5)" },
  { id: "global",     nome: "Global",      tag: "global",     emoji: "🌍", bg: "linear-gradient(135deg,#2563eb,#1d4ed8)", shadow: "rgba(37,99,235,0.5)" },
  { id: "cantores",   nome: "Cantores",    tag: "cantor",     emoji: "🎵", bg: "linear-gradient(135deg,#ea580c,#c2410c)", shadow: "rgba(234,88,12,0.5)" },
  { id: "desporto",   nome: "Desporto",    tag: "atleta",     emoji: "⚽", bg: "linear-gradient(135deg,#0891b2,#0e7490)", shadow: "rgba(8,145,178,0.5)" },
  { id: "animais",    nome: "Animais",     tag: "animal",     emoji: "🐾", bg: "linear-gradient(135deg,#d97706,#b45309)", shadow: "rgba(217,119,6,0.5)" },
  { id: "personagens",nome: "Personagens", tag: "personagem", emoji: "🦸", bg: "linear-gradient(135deg,#db2777,#be185d)", shadow: "rgba(219,39,119,0.5)" },
  { id: "comida",     nome: "Comida",      tag: "comida",     emoji: "🍕", bg: "linear-gradient(135deg,#dc2626,#b91c1c)", shadow: "rgba(220,38,38,0.5)" },
  { id: "marcas",     nome: "Marcas",      tag: "marca",      emoji: "🏷️", bg: "linear-gradient(135deg,#4f46e5,#4338ca)", shadow: "rgba(79,70,229,0.5)" },
  { id: "anime",      nome: "Anime",       tag: "anime",      emoji: "⛩️", bg: "linear-gradient(135deg,#ca8a04,#a16207)", shadow: "rgba(202,138,4,0.5)" },
  { id: "biblia",     nome: "Bíblia",      tag: "biblia",     emoji: "📖", bg: "linear-gradient(135deg,#92400e,#78350f)", shadow: "rgba(146,64,14,0.5)" },
];

export function getItems(tag, difs = ["facil","medio","dificil"]) {
  return QUEM_SOU_EU_DB.filter(i => i.tags.includes(tag) && difs.includes(i.dif));
}

export function getMix() {
  return QUEM_SOU_EU_DB.filter(i => i.tags.includes("mz") || i.tags.includes("global"));
}

export function getDeckForCategory(catId) {
  if (catId === "mix" || !catId) return getMix();
  const cat = CATEGORIAS.find(c => c.id === catId);
  if (!cat || !cat.tag) return getMix();
  return getItems(cat.tag);
}
