// client/games/sporcleMZData.js
// respostas_aceites: array de arrays — cada sub-array = uma resposta válida + sinónimos

export const SPORCLE_CATS = [
  // ─────────────────────────────────────────────────────────
  // CAT 1 — BAIRROS E CIDADES
  // ─────────────────────────────────────────────────────────
  {
    id: "cidades",
    nome: "Bairros e Cidades",
    emoji: "🏘️",
    cor: "#7c5dfa",
    dificuldade: "média",
    perguntas: [
      // ── resposta_curta ──────────────────────────────────
      { id:"c01", tipo:"resposta_curta", tempo:15,
        pergunta:"Qual é a capital de Moçambique?",
        respostas_aceites:[["maputo","lourenco marques","lourenço marques"]] },
      { id:"c02", tipo:"resposta_curta", tempo:15,
        pergunta:"Capital da província de Sofala?",
        respostas_aceites:[["beira","cidade da beira"]] },
      { id:"c03", tipo:"resposta_curta", tempo:15,
        pergunta:"Capital da província de Nampula?",
        respostas_aceites:[["nampula"]] },
      { id:"c04", tipo:"resposta_curta", tempo:15,
        pergunta:"Capital da província de Gaza?",
        respostas_aceites:[["xai-xai","xaixai","xai xai","joao belo"]] },
      { id:"c05", tipo:"resposta_curta", tempo:15,
        pergunta:"Capital da província de Manica?",
        respostas_aceites:[["chimoio","vila pery"]] },
      { id:"c06", tipo:"resposta_curta", tempo:15,
        pergunta:"Capital da província de Tete?",
        respostas_aceites:[["tete"]] },
      { id:"c07", tipo:"resposta_curta", tempo:15,
        pergunta:"Capital da província de Zambézia?",
        respostas_aceites:[["quelimane"]] },
      { id:"c08", tipo:"resposta_curta", tempo:15,
        pergunta:"Capital da província de Niassa?",
        respostas_aceites:[["lichinga","vila cabral"]] },
      { id:"c09", tipo:"resposta_curta", tempo:15,
        pergunta:"Capital da província de Cabo Delgado?",
        respostas_aceites:[["pemba","porto amelia"]] },
      { id:"c10", tipo:"resposta_curta", tempo:15,
        pergunta:"Capital da província de Inhambane?",
        respostas_aceites:[["inhambane"]] },
      { id:"c11", tipo:"resposta_curta", tempo:15,
        pergunta:"Em que província fica a Barragem de Cahora Bassa?",
        respostas_aceites:[["tete"]] },
      { id:"c12", tipo:"resposta_curta", tempo:15,
        pergunta:"Qual é a segunda maior cidade de Moçambique?",
        respostas_aceites:[["matola","Beira"]] },
      { id:"c13", tipo:"resposta_curta", tempo:15,
        pergunta:"Qual cidade costeira é conhecida pelas praias de coral e resorts em Inhambane?",
        respostas_aceites:[["tofo","praia do tofo"]] },
      { id:"c14", tipo:"resposta_curta", tempo:15,
        pergunta:"Em que cidade fica o maior estádio de Moçambique (Estádio do Zimpeto)?",
        respostas_aceites:[["maputo"]] },
      { id:"c15", tipo:"resposta_curta", tempo:15,
        pergunta:"Qual município faz fronteira com a África do Sul e é conhecido pelo jogo?",
        respostas_aceites:[["ponta do ouro","ressano garcia"]] },

      // ── lista ───────────────────────────────────────────
      { id:"c16", tipo:"lista", tempo:60, total:6,
        pergunta:"Nomeia os 6 países que fazem fronteira com Moçambique",
        respostas_aceites:[
          ["tanzania","tanzânia","tanzánia"],
          ["malawi","malaui","malaví"],
          ["zambia","zâmbia","zámbia"],
          ["zimbabwe","zimbabué","zimbabue","zimbaue"],
          ["eswatini","suazilandia","swazilândia","suazilândia","eswatini"],
          ["africa do sul","south africa","ásafrica","sul de africa"],
        ]},
      { id:"c17", tipo:"lista", tempo:60, total:4,
        pergunta:"Nomeia 4 ilhas ou arquipélagos famosos de Moçambique",
        respostas_aceites:[
          ["ilha de mocambique","ilha de moçambique","ilha moçambique","ilha mozambique"],
          ["bazaruto","ilha do bazaruto","arquipelago do bazaruto"],
          ["quirimbas","arquipelago das quirimbas"],
          ["inhaca","ilha da inhaca"],
          ["ibo","ilha do ibo"],
        ]},
      { id:"c18", tipo:"lista", tempo:60, total:4,
        pergunta:"Nomeia 4 bairros populares de Maputo",
        respostas_aceites:[
          ["xipamanine"],
          ["malhazine"],
          ["polana","polana cimento","polana canigo","polana caniço"],
          ["hulene"],
          ["zimpeto"],
          ["chamanculo"],
          ["alto mae","alto maé"],
          ["sommerschield"],
          ["costa do sol"],
          ["albasine"],
        ]},
      { id:"c19", tipo:"lista", tempo:45, total:4,
        pergunta:"Nomeia 4 rios importantes de Moçambique",
        respostas_aceites:[
          ["zambeze","zambezi","rio zambeze"],
          ["limpopo","rio limpopo"],
          ["save","rio save"],
          ["incomati","incomáti","rio incomati"],
          ["lugela"],
          ["rovuma","rio rovuma"],
          ["buzi","rio buzi"],
        ]},
      { id:"c20", tipo:"lista", tempo:45, total:4,
        pergunta:"Nomeia 4 províncias do norte de Moçambique",
        respostas_aceites:[
          ["niassa"],
          ["cabo delgado"],
          ["nampula"],
          ["zambezia","zambézia","zambezia"],
        ]},
      { id:"c21", tipo:"lista", tempo:45, total:3,
        pergunta:"Nomeia 3 províncias do sul de Moçambique",
        respostas_aceites:[
          ["maputo","maputo cidade","cidade de maputo"],
          ["maputo provincia","provincia de maputo","maputo provinc"],
          ["gaza"],
          ["inhambane"],
        ]},
      { id:"c22", tipo:"lista", tempo:60, total:5,
        pergunta:"Nomeia 5 destinos turísticos de praias em Moçambique",
        respostas_aceites:[
          ["tofo","praia do tofo"],
          ["vilanculos","vilanculo"],
          ["ponta do ouro"],
          ["pemba"],
          ["bazaruto"],
          ["beira"],
          ["arquipélago de bazaruto"],
          ["inhambane"],
          ["nacala"],
          ["Bilene","praia do bilene"],
        ]},
      { id:"c23", tipo:"lista", tempo:45, total:3,
        pergunta:"Nomeia 3 distritos municipais de Maputo",
        respostas_aceites:[
          ["kampfumo","ka mpfumo","ka-mpfumo"],
          ["kamavota","ka mavota","ka-mavota"],
          ["kamubukwana","ka mubukwana"],
          ["kamaxaquene","ka maxaquene"],
          ["kanyaka","ka nyaka","katembe","ka tembe"],
        ]},
      { id:"c24", tipo:"lista", tempo:60, total:5,
        pergunta:"Nomeia 5 cidades costeiras de Moçambique",
        respostas_aceites:[
          ["maputo"],
          ["beira"],
          ["nampula"],["nacala"],
          ["pemba"],
          ["quelimane"],
          ["inhambane"],
          ["mocambique","moçambique","ilha de mocambique"],
        ]},
      { id:"c25", tipo:"lista", tempo:45, total:3,
        pergunta:"Nomeia 3 reservas naturais ou parques nacionais de Moçambique",
        respostas_aceites:[
          ["gorongosa","parque da gorongosa","gorongosa national park"],
          ["niassa","reserva do niassa","reserva nacional do niassa"],
          ["zinave","parque nacional do zinave"],
          ["banhine","parque nacional do banhine"],
          ["bazaruto","parque nacional do bazaruto","arquipelago do bazaruto"],
          ["quirimbas","parque nacional das quirimbas"],
        ]},
    ],
  },

  // ─────────────────────────────────────────────────────────
  // CAT 2 — MÚSICA MZ
  // ─────────────────────────────────────────────────────────
  {
    id: "musica",
    nome: "Música MZ",
    emoji: "🎵",
    cor: "#00e5b0",
    dificuldade: "fácil",
    perguntas: [
      // ── resposta_curta ──────────────────────────────────
      { id:"m01", tipo:"resposta_curta", tempo:15,
        pergunta:"Qual é o género musical urbano mais popular em Maputo?",
        respostas_aceites:[["pandza","panda","pandza music"]] },
      { id:"m02", tipo:"resposta_curta", tempo:15,
        pergunta:"Qual é o nome do cantor moçambicano conhecido como 'Rei da Marrabenta'?",
        respostas_aceites:[["wazimbo","wazimbo ngungunyane"]] },
      { id:"m03", tipo:"resposta_curta", tempo:15,
        pergunta:"Qual género musical tem origem na etnia Chopi e usa o instrumento timbila?",
        respostas_aceites:[["timbila","musica timbila"]] },
      { id:"m04", tipo:"resposta_curta", tempo:15,
        pergunta:"Qual cantora MZ ficou famosa pelo álbum 'Balada de Amor ao Vento'?",
        respostas_aceites:[["mingas"]] },
      { id:"m05", tipo:"resposta_curta", tempo:15,
        pergunta:"Qual rapper moçambicano ficou famoso pelo álbum 'Muthiana Omukhulu'?",
        respostas_aceites:[["azagaia","edson da luz"]] },
      { id:"m06", tipo:"resposta_curta", tempo:15,
        pergunta:"Qual cantora MZ é conhecida pela música 'Djama'?",
        respostas_aceites:[["neyma"]] },
      { id:"m07", tipo:"resposta_curta", tempo:15,
        pergunta:"Qual é o nome do cantor MZ que popularizou a música 'Nguiane'?",
        respostas_aceites:[["mr bow","mister bow","mrbow"]] },
      { id:"m08", tipo:"resposta_curta", tempo:15,
        pergunta:"Qual DJ/produtor MZ é conhecido como 'DJ Ziqo'?",
        respostas_aceites:[["ziqo","dj ziqo"]] },
      { id:"m09", tipo:"resposta_curta", tempo:15,
        pergunta:"Qual cantora MZ é conhecida pela música 'Sou Feliz'?",
        respostas_aceites:[["lizha james","lizha"]] },
      { id:"m10", tipo:"resposta_curta", tempo:15,
        pergunta:"Como se chama o género musical tradicional de Cabo Delgado dançado em celebrações islâmicas?",
        respostas_aceites:[["tufo"]] },
      { id:"m11", tipo:"resposta_curta", tempo:15,
        pergunta:"Qual cantor MZ é conhecido pela música 'Soluço'?",
        respostas_aceites:[["stewart sukuma","sukuma"]] },
      { id:"m12", tipo:"resposta_curta", tempo:15,
        pergunta:"Qual artista MZ é conhecida por 'Meu Amor' e é um dos rostos do AfroPoP em MZ?",
        respostas_aceites:[["tamyris","tamyris moiane"]] },
      { id:"m13", tipo:"resposta_curta", tempo:15,
        pergunta:"Qual rapper MZ ficou popular com 'Bem-Vindo a Maputo'?",
        respostas_aceites:[["mc roger","mc roger"]] },
      { id:"m14", tipo:"resposta_curta", tempo:15,
        pergunta:"Qual artista MZ ficou conhecido com a música 'Nyamurate'?",
        respostas_aceites:[["laylizzy","laylizzy davilson"]] },
      { id:"m15", tipo:"resposta_curta", tempo:15,
        pergunta:"Qual é o instrumento de cordas dedilhadas tradicional usado pelos Chopi?",
        respostas_aceites:[["timbila","mbira","xitende"]] },

      // ── lista ───────────────────────────────────────────
      { id:"m16", tipo:"lista", tempo:45, total:4,
        pergunta:"Nomeia 4 géneros musicais com origem em Moçambique",
        respostas_aceites:[
          ["marrabenta"],
          ["pandza","panda"],
          ["tufo"],
          ["timbila"],
          ["mapiko"],
          ["xigubo"],
          ["xibelane"],
        ]},
      { id:"m17", tipo:"lista", tempo:60, total:6,
        pergunta:"Nomeia 6 artistas/cantores moçambicanos",
        respostas_aceites:[
          ["neyma"],
          ["lizha james","lizha"],
          ["mr bow","mister bow"],
          ["azagaia"],
          ["wazimbo"],
          ["ziqo","dj ziqo"],
          ["laylizzy"],
          ["tamyris","tamyris moiane"],
          ["mr kuka","kuka"],
          ["hot blaze"],
          ["twenty fingers"],
          ["bander"],
          ["mc roger"],
          ["stewart sukuma","sukuma"],
          ["mingas"],
          ["marllen"],
          ["percella"],
          ["lourena nhate","lourena"],
          ["dygo boy","dygo"],
          ["edu all talents","edu"],
        ]},
      { id:"m18", tipo:"lista", tempo:45, total:4,
        pergunta:"Nomeia 4 cantoras (feminino) moçambicanas",
        respostas_aceites:[
          ["neyma"],
          ["lizha james","lizha"],
          ["tamyris","tamyris moiane"],
          ["mingas"],
          ["marllen"],
          ["percella"],
          ["lourena nhate","lourena"],
          ["dama do bling"],
        ]},
      { id:"m19", tipo:"lista", tempo:45, total:4,
        pergunta:"Nomeia 4 rappers ou artistas de hip-hop moçambicanos",
        respostas_aceites:[
          ["azagaia"],
          ["laylizzy"],
          ["mc roger","mc roger"],
          ["hot blaze"],
          ["ubakka","justino ubakka"],
          ["mr bow","mister bow"],
          ["bander"],
          ["dygo boy","dygo"],
        ]},
      { id:"m20", tipo:"lista", tempo:30, total:3,
        pergunta:"Nomeia 3 instrumentos musicais tradicionais de Moçambique",
        respostas_aceites:[
          ["timbila"],
          ["mbira"],
          ["xitende"],
          ["ngoma"],
          ["nhacasso"],
          ["lupembe"],
        ]},
      { id:"m21", tipo:"lista", tempo:45, total:4,
        pergunta:"Nomeia 4 artistas africanos (não MZ) muito populares em Moçambique",
        respostas_aceites:[
          ["burna boy"],
          ["wizkid","wiz kid"],
          ["diamond platnumz","diamond"],
          ["c4 pedro","c4"],
          ["anselmo ralph","anselmo"],
          ["nelson freitas"],
          ["calema"],
          ["davido"],
        ]},
      { id:"m22", tipo:"lista", tempo:45, total:3,
        pergunta:"Nomeia 3 danças tradicionais de Moçambique",
        respostas_aceites:[
          ["mapiko"],
          ["tufo"],
          ["xigubo"],
          ["xibelane"],
          ["marrabenta"],
          ["timbila"],
        ]},
      { id:"m23", tipo:"lista", tempo:45, total:4,
        pergunta:"Nomeia 4 artistas MZ conhecidos por música gospel ou cristã",
        respostas_aceites:[
          ["valdemiro jose","valdemiro"],
          ["deborah duarte","deborah"],
          ["yadah"],
          ["nuno abdul","nuno"],
          ["edmazia","edmazia mayembe"],
        ]},
      { id:"m24", tipo:"lista", tempo:30, total:3,
        pergunta:"Nomeia 3 rótulos de cerveja moçambicana (que se ouvem em músicas MZ)",
        respostas_aceites:[
          ["2m","dois m"],
          ["laurentina"],
          ["tipo tinto","tipo"],
        ]},
      { id:"m25", tipo:"lista", tempo:45, total:4,
        pergunta:"Nomeia 4 podcasts ou influencers MZ conhecidos nas redes sociais",
        respostas_aceites:[
          ["guyzelh","guyzelh ramos"],
          ["cardo","cardo podcast"],
          ["maxh","maxh 258"],
          ["catamo"],
          ["salensio"],
          ["lizha james","lizha"],
        ]},
    ],
  },

  // ─────────────────────────────────────────────────────────
  // CAT 3 — GÍRIAS E EXPRESSÕES
  // ─────────────────────────────────────────────────────────
  {
    id: "girias",
    nome: "Gírias e Expressões",
    emoji: "💬",
    cor: "#f59e0b",
    dificuldade: "fácil",
    perguntas: [
      // ── resposta_curta ──────────────────────────────────
      { id:"g01", tipo:"resposta_curta", tempo:15,
        pergunta:"O que significa 'Kanimambo' em Changana?",
        respostas_aceites:[["obrigado","obrigado/a"]] },
      { id:"g02", tipo:"resposta_curta", tempo:15,
        pergunta:"O que significa 'Mboa' na gíria de Maputo?",
        respostas_aceites:[["rapariga","namorada","miuda","miúda","girl"]] },
      { id:"g03", tipo:"resposta_curta", tempo:15,
        pergunta:"O que significa 'Xilado' na gíria moçambicana?",
        respostas_aceites:[["cansado","sem dinheiro","lixado","exausto","sem fundos"]] },
      { id:"g04", tipo:"resposta_curta", tempo:15,
        pergunta:"O que significa 'Nyama' em Changana e Ronga?",
        respostas_aceites:[["carne"]] },
      { id:"g05", tipo:"resposta_curta", tempo:15,
        pergunta:"O que significa 'Salani Kahle' em Changana?",
        respostas_aceites:[["adeus","fiquem bem","ate logo","tchau"]] },
      { id:"g06", tipo:"resposta_curta", tempo:15,
        pergunta:"O que significa 'Pela' na gíria de Maputo?",
        respostas_aceites:[["dinheiro","massa","guita"]] },
      { id:"g07", tipo:"resposta_curta", tempo:15,
        pergunta:"O que significa 'Boah' na gíria moçambicana?",
        respostas_aceites:[["boa","bom","fixe","top"]] },
      { id:"g08", tipo:"resposta_curta", tempo:15,
        pergunta:"O que significa 'Mana' quando usado como vocativo no contexto moçambicano?",
        respostas_aceites:[["irma","amiga","mana","colega"]] },
      { id:"g09", tipo:"resposta_curta", tempo:15,
        pergunta:"Como se diz 'Bom dia' em Changana?",
        respostas_aceites:[["xewani","sawubona","bom dia changana"]] },
      { id:"g10", tipo:"resposta_curta", tempo:15,
        pergunta:"O que é um 'Chapa' em Moçambique?",
        respostas_aceites:[["transporte publico","mini autocarro","minibus","transporte coletivo","chapa 100"]] },
      { id:"g11", tipo:"resposta_curta", tempo:15,
        pergunta:"O que significa 'Txopela' em Moçambique?",
        respostas_aceites:[["mototaxi","moto taxi","motociclo taxi","txopela"]] },
      { id:"g12", tipo:"resposta_curta", tempo:15,
        pergunta:"O que é o 'Lobolo' na cultura moçambicana?",
        respostas_aceites:[["dote","bridewealth","preco da noiva","noiva price","pagamento para casar"]] },
      { id:"g13", tipo:"resposta_curta", tempo:15,
        pergunta:"O que significa 'Kuyimba' em Changana?",
        respostas_aceites:[["cantar","musica"]] },
      { id:"g14", tipo:"resposta_curta", tempo:15,
        pergunta:"O que é o 'Xitique' na cultura moçambicana?",
        respostas_aceites:[["poupanca coletiva","sistema de poupanca","kitty","vaquinha"]] },
      { id:"g15", tipo:"resposta_curta", tempo:15,
        pergunta:"O que significa 'Malandro' na gíria MZ (contexto neutro)?",
        respostas_aceites:[["espertalhao","esperto","malandro","fixolas","safado"]] },

      // ── lista ───────────────────────────────────────────
      { id:"g16", tipo:"lista", tempo:45, total:4,
        pergunta:"Nomeia 4 formas de dizer 'amigo' ou 'colega' na gíria MZ",
        respostas_aceites:[
          ["mano","manu"],
          ["bro"],
          ["parceiro"],
          ["chegou","cheg"],
          ["maninho"],
          ["cu"],
          ["bodas"],
        ]},
      { id:"g17", tipo:"lista", tempo:45, total:4,
        pergunta:"Nomeia 4 palavras MZ para dizer que algo é bom/fixe",
        respostas_aceites:[
          ["boah","boa"],
          ["massa"],
          ["fixe"],
          ["top"],
          ["direto"],
          ["show"],
          ["na vibe"],
          ["certo"],
        ]},
      { id:"g18", tipo:"lista", tempo:45, total:4,
        pergunta:"Nomeia 4 pratos típicos moçambicanos",
        respostas_aceites:[
          ["matapa"],
          ["xima"],
          ["caril de amendoim","caril amendoim"],
          ["galinha zambeziana","galinha a zambeziana"],
          ["frango cafreal","frango a cafreal"],
          ["chamussas"],
          ["badjias"],
          ["lagosta"],
        ]},
      { id:"g19", tipo:"lista", tempo:30, total:3,
        pergunta:"Nomeia 3 línguas bantu faladas em Moçambique",
        respostas_aceites:[
          ["changana"],
          ["ronga"],
          ["macua","makua"],
          ["sena"],
          ["ndau"],
          ["tswa"],
          ["chewa"],
          ["yao"],
          ["lomue"],
          ["makonde"],
        ]},
      { id:"g20", tipo:"lista", tempo:30, total:3,
        pergunta:"Nomeia 3 moedas ou formas de pagamento usadas no dia a dia em MZ",
        respostas_aceites:[
          ["metical","mt","meticais"],
          ["mpesa","m-pesa"],
          ["emola","e-mola"],
          ["ponto 24","ponto24","multicaixa"],
          ["rand"],
        ]},
      { id:"g21", tipo:"lista", tempo:45, total:4,
        pergunta:"Nomeia 4 expressões moçambicanas de cumprimento",
        respostas_aceites:[
          ["kanimambo"],
          ["salani kahle","salani"],
          ["xewani"],
          ["minjani","minjane"],
          ["nhani"],
          ["como esta","como estás","como vai"],
        ]},
      { id:"g22", tipo:"lista", tempo:45, total:4,
        pergunta:"Nomeia 4 marcas ou produtos tipicamente moçambicanos",
        respostas_aceites:[
          ["2m","dois m","cerveja 2m"],
          ["laurentina"],
          ["tipo tinto","tipo"],
          ["caju","suco de caju"],
          ["movitel"],
          ["tmcel"],
          ["vodacom"],
          ["piri piri","piri-piri"],
        ]},
      { id:"g23", tipo:"lista", tempo:45, total:4,
        pergunta:"Nomeia 4 palavras que descrevem comportamentos típicos na gíria MZ",
        respostas_aceites:[
          ["xilado"],
          ["malandro"],
          ["na frente","nafrente"],
          ["desconfiar","desconfiado"],
          ["bater o pe","bater o pé","bater pe"],
          ["fazer esquema","esquema"],
          ["mandar bala"],
        ]},
      { id:"g24", tipo:"lista", tempo:45, total:4,
        pergunta:"Nomeia 4 objectos do dia a dia em Moçambique com nomes locais específicos",
        respostas_aceites:[
          ["capulana"],
          ["chapa"],
          ["txopela","txopela"],
          ["catana"],
          ["pilao","pilão"],
          ["baraca","barraca"],
          ["machamba"],
        ]},
      { id:"g25", tipo:"lista", tempo:30, total:3,
        pergunta:"Nomeia 3 festas ou celebrações culturais em Moçambique",
        respostas_aceites:[
          ["lobolo"],
          ["xitique"],
          ["mapiko"],
          ["tufo"],
          ["marrabenta"],
          ["festa da independencia","25 de junho","independencia"],
          ["festa da paz","4 de outubro","dia da paz"],
        ]},
    ],
  },
];
