// MZ PARTY GAMES — Quem Sou Eu — Base de dados única (554 itens)
// Partilhado por client + server. Cada item: { nome, tags[], dif, nota }.
// tags: mz, global, cantor, atleta, ator, lider, influencer, personagem,
//   animal, comida, marca, anime, biblia, nostalgia, lugar, objeto, livro
// dif: facil | medio | dificil

export const QUEM_SOU_EU_DB = [

  // ── MZ CANTORES ───────────────────────────────────────────
  { nome: "Stewart Sukuma",        tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Neyma",                 tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Lizha James",           tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Marllen",               tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Lourena Nhate",         tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Ziqo",                  tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Mr. Bow",               tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "MC Roger",              tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Azagaia",               tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Dama do Bling",         tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Tamyris Moiane",        tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Hernâni da Silva",      tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Bander",                tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Bangla 10",             tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Mr. Kuka",              tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Kiba the Seven",        tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Laylizzy",              tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Akon G",                tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Kamane Kamas",          tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Hot Blaze",             tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Twenty Fingers",        tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Doppaz",                tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Percella",              tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Melony",                tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Denilson",              tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Alcy Caluamba",         tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Deborah Duarte",        tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Sheldon",               tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Justino Ubakka",        tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Edmázia Mayembe",       tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Pérola",                tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Stefânia Leonel",       tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Dygo Boy",              tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Shabba Wonder",         tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "King Cizzy",            tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Kenny Yuran",           tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Edu All Talents",       tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Edy Puff",              tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Puto Aires",            tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Djimetta",              tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Valentino De La Vega",  tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Feliciano dos Santos",  tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Ghorwane",              tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Fany Pfumo",            tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Dilon Djindji",         tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Iveth",                 tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Nuno Abdul",            tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Yadah",                 tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Cheny",                 tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Tio Edson",             tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Gito",                  tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Zena Bacar",            tags: ["mz","cantor"],              dif: "facil", nota: "" },
  { nome: "Jay Argh",              tags: ["mz","cantor"],              dif: "facil", nota: "" },

  // ── MZ LÍDERES ────────────────────────────────────────────
  { nome: "Samora Machel",         tags: ["mz","lider"],               dif: "facil", nota: "" },
  { nome: "Eduardo Mondlane",      tags: ["mz","lider"],               dif: "facil", nota: "" },
  { nome: "Joaquim Chissano",      tags: ["mz","lider"],               dif: "facil", nota: "" },
  { nome: "Armando Guebuza",       tags: ["mz","lider"],               dif: "facil", nota: "" },
  { nome: "Filipe Nyusi",          tags: ["mz","lider"],               dif: "facil", nota: "" },
  { nome: "Graça Machel",          tags: ["mz","lider"],               dif: "facil", nota: "" },
  { nome: "Venâncio Mondlane",     tags: ["mz","lider"],               dif: "facil", nota: "" },
  { nome: "Daniel Chapo",          tags: ["mz","lider"],               dif: "facil", nota: "" },
  { nome: "Josina Machel",         tags: ["mz","lider"],               dif: "facil", nota: "" },
  { nome: "Afonso Dhlakama",       tags: ["mz","lider"],               dif: "facil", nota: "" },
  { nome: "Mia Couto",             tags: ["mz","lider"],               dif: "facil", nota: "" },
  { nome: "Paulina Chiziane",      tags: ["mz","lider"],               dif: "facil", nota: "" },
  { nome: "Mário Coluna",          tags: ["mz","lider"],               dif: "facil", nota: "" },
  { nome: "Lurdes Mutola",         tags: ["mz","lider"],               dif: "facil", nota: "" },

  // ── MZ ATLETAS ────────────────────────────────────────────
  { nome: "Tico-Tico",             tags: ["mz","atleta"],              dif: "facil", nota: "" },
  { nome: "Chiquinho Conde",       tags: ["mz","atleta"],              dif: "facil", nota: "" },
  { nome: "Geny Catamo",           tags: ["mz","atleta"],              dif: "facil", nota: "" },
  { nome: "Reinildo Mandava",      tags: ["mz","atleta"],              dif: "facil", nota: "" },

  // ── MZ INFLUENCERS ────────────────────────────────────────
  { nome: "Guyzelh Ramos",         tags: ["mz","influencer"],          dif: "facil", nota: "" },
  { nome: "Maxh 258",              tags: ["mz","influencer"],          dif: "facil", nota: "" },
  { nome: "Armando e Daniela",     tags: ["mz","influencer"],          dif: "facil", nota: "" },
  { nome: "Victor Renér",          tags: ["mz","influencer"],          dif: "facil", nota: "" },
  { nome: "Igor Idelson",          tags: ["mz","influencer"],          dif: "facil", nota: "" },
  { nome: "Noslen Araújo",         tags: ["mz","influencer"],          dif: "facil", nota: "" },
  { nome: "Maira Santos",          tags: ["mz","influencer"],          dif: "facil", nota: "" },
  { nome: "Cardo Podcast",         tags: ["mz","influencer"],          dif: "facil", nota: "" },
  { nome: "Stélio Leonel",         tags: ["mz","influencer"],          dif: "facil", nota: "" },
  { nome: "Júlio Magalhães",       tags: ["mz","influencer"],          dif: "facil", nota: "" },
  { nome: "Gilberto Mendes",       tags: ["mz","influencer"],          dif: "facil", nota: "" },
  { nome: "Mana Cecy",             tags: ["mz","influencer"],          dif: "facil", nota: "" },

  // ── CANTORES LUSÓFONOS / AFRICANOS ────────────────────────
  { nome: "C4 Pedro",              tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Anselmo Ralph",         tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Nelson Freitas",        tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Calema",                tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Matias Damásio",        tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Dji Tafinha",           tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Plútonio",              tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Yasmine",               tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Anna Joyce",            tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Yola Semedo",           tags: ["global","cantor"],          dif: "facil", nota: "" },

  // ── MZ LUGARES ────────────────────────────────────────────
  { nome: "Xipamanine",            tags: ["mz","lugar"],               dif: "dificil", nota: "" },
  { nome: "Museu",                 tags: ["mz","lugar"],               dif: "dificil", nota: "" },
  { nome: "Malhazine",             tags: ["mz","lugar"],               dif: "dificil", nota: "" },
  { nome: "Polana",                tags: ["mz","lugar"],               dif: "dificil", nota: "" },
  { nome: "Chamanculo",            tags: ["mz","lugar"],               dif: "dificil", nota: "" },
  { nome: "Alto-Maé",              tags: ["mz","lugar"],               dif: "dificil", nota: "" },
  { nome: "Zimpeto",               tags: ["mz","lugar"],               dif: "dificil", nota: "" },
  { nome: "Maxaquene",             tags: ["mz","lugar"],               dif: "dificil", nota: "" },
  { nome: "Bilene",                tags: ["mz","lugar"],               dif: "dificil", nota: "" },
  { nome: "Tofo",                  tags: ["mz","lugar"],               dif: "dificil", nota: "" },
  { nome: "Ponta do Ouro",         tags: ["mz","lugar"],               dif: "dificil", nota: "" },

  // ── MZ COMIDA ─────────────────────────────────────────────
  { nome: "Matapa",                tags: ["mz","comida"],              dif: "facil", nota: "" },
  { nome: "Xima",                  tags: ["mz","comida"],              dif: "facil", nota: "" },
  { nome: "Chamussas",             tags: ["mz","comida"],              dif: "facil", nota: "" },
  { nome: "Badjias",               tags: ["mz","comida"],              dif: "facil", nota: "" },
  { nome: "Pão com Badjia",        tags: ["mz","comida"],              dif: "facil", nota: "" },
  { nome: "Maheu",                 tags: ["mz","comida"],              dif: "facil", nota: "" },
  { nome: "Piri-Piri",             tags: ["mz","comida"],              dif: "facil", nota: "" },
  { nome: "2M",                    tags: ["mz","comida"],              dif: "facil", nota: "" },
  { nome: "Laurentina",            tags: ["mz","comida"],              dif: "facil", nota: "" },
  { nome: "Tipo (Tinto)",          tags: ["mz","comida"],              dif: "facil", nota: "" },
  { nome: "Caju",                  tags: ["mz","comida"],              dif: "facil", nota: "" },
  { nome: "Tseke",                 tags: ["mz","comida"],              dif: "facil", nota: "" },
  { nome: "Quiabo",                tags: ["mz","comida"],              dif: "facil", nota: "" },
  { nome: "Mandioca",              tags: ["mz","comida"],              dif: "facil", nota: "" },
  { nome: "Matoritori",            tags: ["mz","comida"],              dif: "facil", nota: "" },
  { nome: "Mafura",                tags: ["mz","comida"],              dif: "facil", nota: "" },
  { nome: "Mboa",                  tags: ["mz","comida"],              dif: "facil", nota: "" },
  { nome: "Canhu",                 tags: ["mz","comida"],              dif: "facil", nota: "" },

  // ── MZ OBJETOS ────────────────────────────────────────────
  { nome: "Capulana",              tags: ["mz","objeto"],              dif: "dificil", nota: "" },
  { nome: "Chapa",                 tags: ["mz","objeto"],              dif: "dificil", nota: "" },
  { nome: "Txopela",               tags: ["mz","objeto"],              dif: "dificil", nota: "" },
  { nome: "Curandeiro",            tags: ["mz","objeto"],              dif: "dificil", nota: "" },
  { nome: "Barraca",               tags: ["mz","objeto"],              dif: "dificil", nota: "" },
  { nome: "Catana",                tags: ["mz","objeto"],              dif: "dificil", nota: "" },

  // ── ANIMAIS ───────────────────────────────────────────────
  { nome: "Mamba",                 tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Crocodilo",             tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Hipopótamo",            tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Elefante",              tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Leão",                  tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Zebra",                 tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Girafa",                tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Impala",                tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Rinoceronte",           tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Macaco",                tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Camaleão",              tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Mosquito",              tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Tartaruga Marinha",     tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Caranguejo",            tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Lagosta",               tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Tubarão-Baleia",        tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Golfinho",              tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Flamingo",              tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Búfalo",                tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Cão",                   tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Galinha",               tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Cabrito",               tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Aranha",                tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Cobra",                 tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Morcego",               tags: ["animal"],                   dif: "facil", nota: "" },
  { nome: "Sapo",                  tags: ["animal"],                   dif: "facil", nota: "" },

  // ── GLOBAL CANTORES ───────────────────────────────────────
  { nome: "Michael Jackson",       tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Elvis Presley",         tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Madonna",               tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Bob Marley",            tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Freddie Mercury",       tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Beyoncé",               tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Rihanna",               tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Taylor Swift",          tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Drake",                 tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Eminem",                tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Jay-Z",                 tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Kanye West",            tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Adele",                 tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Lady Gaga",             tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Bruno Mars",            tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Justin Bieber",         tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "The Weeknd",            tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Ed Sheeran",            tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Billie Eilish",         tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Shakira",               tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Nicki Minaj",           tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Cardi B",               tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Post Malone",           tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Snoop Dogg",            tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "50 Cent",               tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Tupac",                 tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Notorious B.I.G.",      tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Amy Winehouse",         tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Britney Spears",        tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Chris Brown",           tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Dua Lipa",              tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Bad Bunny",             tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Ariana Grande",         tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Kendrick Lamar",        tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Travis Scott",          tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Daddy Yankee",          tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Ice Spice",             tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Central Cee",           tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Tems",                  tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Tyla",                  tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Future",                tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Burna Boy",             tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Doja Cat",              tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Lil Baby",              tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "PARTYNEXTDOOR",         tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Brent Faiyaz",          tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Don Toliver",           tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "21 Savage",             tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Megan Thee Stallion",   tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Anitta",                tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Virgínia",              tags: ["global","influencer"],      dif: "facil", nota: "" },
  { nome: "Ludmilla",              tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Chico Moedas",          tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Whindersson Nunes",     tags: ["global","influencer"],      dif: "facil", nota: "" },
  { nome: "Alok",                  tags: ["global","cantor"],          dif: "facil", nota: "" },
  { nome: "Wesley Safadão",        tags: ["global","cantor"],          dif: "facil", nota: "" },

  // ── GLOBAL ATLETAS ────────────────────────────────────────
  { nome: "Cristiano Ronaldo",     tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Lionel Messi",          tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Neymar",                tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Kylian Mbappé",         tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Pelé",                  tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Maradona",              tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Ronaldinho",            tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "David Beckham",         tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Zinedine Zidane",       tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Michael Jordan",        tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "LeBron James",          tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Kobe Bryant",           tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Stephen Curry",         tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Usain Bolt",            tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Muhammad Ali",          tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Mike Tyson",            tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Floyd Mayweather",      tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Conor McGregor",        tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Serena Williams",       tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Tiger Woods",           tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Lewis Hamilton",        tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Ayrton Senna",          tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Roger Federer",         tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "Rafael Nadal",          tags: ["global","atleta"],          dif: "facil", nota: "" },
  { nome: "The Rock",              tags: ["global","atleta","ator"],   dif: "facil", nota: "" },
  { nome: "John Cena",             tags: ["global","atleta","ator"],   dif: "facil", nota: "" },

  // ── GLOBAL ATORES ─────────────────────────────────────────
  { nome: "Leonardo DiCaprio",     tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Tom Hanks",             tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Brad Pitt",             tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Will Smith",            tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Ryan Reynolds",         tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Keanu Reeves",          tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Tom Cruise",            tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Robert Downey Jr.",     tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Johnny Depp",           tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Morgan Freeman",        tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Denzel Washington",     tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Angelina Jolie",        tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Scarlett Johansson",    tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Margot Robbie",         tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Zendaya",               tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Jennifer Lawrence",     tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Emma Watson",           tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Gal Gadot",             tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Jim Carrey",            tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Kevin Hart",            tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Adam Sandler",          tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Robin Williams",        tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Eddie Murphy",          tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Arnold Schwarzenegger", tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Sylvester Stallone",    tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Jackie Chan",           tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Bruce Lee",             tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Marilyn Monroe",        tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Audrey Hepburn",        tags: ["global","ator"],            dif: "facil", nota: "" },
  { nome: "Charles Chaplin",       tags: ["global","ator"],            dif: "facil", nota: "" },

  // ── GLOBAL INFLUENCERS ────────────────────────────────────
  { nome: "Kim Kardashian",        tags: ["global","influencer"],      dif: "facil", nota: "" },
  { nome: "Kylie Jenner",          tags: ["global","influencer"],      dif: "facil", nota: "" },
  { nome: "MrBeast",               tags: ["global","influencer"],      dif: "facil", nota: "" },
  { nome: "Oprah Winfrey",         tags: ["global","influencer"],      dif: "facil", nota: "" },
  { nome: "Gordon Ramsay",         tags: ["global","influencer"],      dif: "facil", nota: "" },
  { nome: "KSI",                   tags: ["global","influencer"],      dif: "facil", nota: "" },
  { nome: "Logan Paul",            tags: ["global","influencer"],      dif: "facil", nota: "" },
  { nome: "IShowSpeed",            tags: ["global","influencer"],      dif: "facil", nota: "" },
  { nome: "Kai Cenat",             tags: ["global","influencer"],      dif: "facil", nota: "" },
  { nome: "Khaby Lame",            tags: ["global","influencer"],      dif: "facil", nota: "" },

  // ── GLOBAL LÍDERES ────────────────────────────────────────
  { nome: "Nelson Mandela",        tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Barack Obama",          tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Donald Trump",          tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Vladimir Putin",        tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Rainha Elizabeth",      tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Princesa Diana",        tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Papa Francisco",        tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Napoleão Bonaparte",    tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Cleópatra",             tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Júlio César",           tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Alexandre o Grande",    tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Adolf Hitler",          tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Albert Einstein",       tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Nikola Tesla",          tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Leonardo da Vinci",     tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Marie Curie",           tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Charles Darwin",        tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Elon Musk",             tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Jeff Bezos",            tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Bill Gates",            tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Steve Jobs",            tags: ["global","lider"],           dif: "facil", nota: "" },
  { nome: "Mark Zuckerberg",       tags: ["global","lider"],           dif: "facil", nota: "" },

  // ── GLOBAL PERSONAGENS ────────────────────────────────────
  { nome: "Batman",                tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Superman",              tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Spider-Man",            tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Hulk",                  tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Thor",                  tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Capitão América",       tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Homem de Ferro",        tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Deadpool",              tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Wolverine",             tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Thanos",                tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Joker",                 tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Darth Vader",           tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Harley Quinn",          tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Venom",                 tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Loki",                  tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Harry Potter",          tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Hermione Granger",      tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Voldemort",             tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Dumbledore",            tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Gandalf",               tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Sherlock Holmes",       tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Robin Hood",            tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Mickey Mouse",          tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Elsa",                  tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Woody",                 tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Buzz Lightyear",        tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Nemo",                  tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Gru",                   tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Stitch",                tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Moana",                 tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Rapunzel",              tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Pikachu",               tags: ["global","personagem","anime"], dif: "facil", nota: "" },
  { nome: "Mario",                 tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Luigi",                 tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Sonic",                 tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Pac-Man",               tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Homer Simpson",         tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Bart Simpson",          tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "SpongeBob",             tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Bugs Bunny",            tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Scooby-Doo",            tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Peter Griffin",         tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Rick Sanchez",          tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Baby Yoda",             tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Walter White",          tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Jon Snow",              tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Daenerys Targaryen",    tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Tommy Shelby",          tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Jack Sparrow",          tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Drácula",               tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Frankenstein",          tags: ["global","personagem"],      dif: "facil", nota: "" },
  { nome: "Simba",                 tags: ["global","personagem","nostalgia"], dif: "facil", nota: "" },
  { nome: "Shrek",                 tags: ["global","personagem","nostalgia"], dif: "facil", nota: "" },
  { nome: "Peter Pan",             tags: ["global","personagem","nostalgia"], dif: "facil", nota: "" },
  { nome: "Pinóquio",              tags: ["global","personagem","nostalgia"], dif: "facil", nota: "" },
  { nome: "Kuzco (A Nova Onda do Imperador)", tags: ["global","personagem","nostalgia"], dif: "facil", nota: "" },

  // ── GLOBAL COMIDA ─────────────────────────────────────────
  { nome: "Pizza",                 tags: ["global","comida"],          dif: "facil", nota: "" },
  { nome: "Hambúrguer",            tags: ["global","comida"],          dif: "facil", nota: "" },
  { nome: "Sushi",                 tags: ["global","comida"],          dif: "facil", nota: "" },
  { nome: "Chocolate",             tags: ["global","comida"],          dif: "facil", nota: "" },
  { nome: "Coca-Cola",             tags: ["global","comida"],          dif: "facil", nota: "" },
  { nome: "Gelado",                tags: ["global","comida"],          dif: "facil", nota: "" },
  { nome: "Café",                  tags: ["global","comida"],          dif: "facil", nota: "" },
  { nome: "Cerveja",               tags: ["global","comida"],          dif: "facil", nota: "" },
  { nome: "Taco",                  tags: ["global","comida"],          dif: "facil", nota: "" },
  { nome: "Croissant",             tags: ["global","comida"],          dif: "facil", nota: "" },

  // ── MARCAS GLOBAIS ────────────────────────────────────────
  { nome: "McDonald's",            tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "KFC",                   tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Burger King",           tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Pizza Hut",             tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Starbucks",             tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Pepsi",                 tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Fanta",                 tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Sprite",                tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Nutella",               tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Apple",                 tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Google",                tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Samsung",               tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Microsoft",             tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "WhatsApp",              tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Instagram",             tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "TikTok",                tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "YouTube",               tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Facebook",              tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Netflix",               tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Spotify",               tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "PlayStation",           tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Xbox",                  tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Ferrari",               tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Lamborghini",           tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Mercedes",              tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "BMW",                   tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Toyota",                tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Honda",                 tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Tesla",                 tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Nike",                  tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Adidas",                tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Puma",                  tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Gucci",                 tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Louis Vuitton",         tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Rolex",                 tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Barbie",                tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "LEGO",                  tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Amazon",                tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "Disney",                tags: ["marca","global"],           dif: "facil", nota: "" },
  { nome: "WWE",                   tags: ["marca","global"],           dif: "facil", nota: "" },

  // ── MZ MARCAS ─────────────────────────────────────────────
  { nome: "Mcel",                  tags: ["marca","mz"],               dif: "facil", nota: "" },
  { nome: "Vodacom",               tags: ["marca","mz"],               dif: "facil", nota: "" },
  { nome: "Tmcel",                 tags: ["marca","mz"],               dif: "facil", nota: "" },
  { nome: "2M (marca)",            tags: ["marca","mz"],               dif: "facil", nota: "" },
  { nome: "Laurentina (marca)",    tags: ["marca","mz"],               dif: "facil", nota: "" },
  { nome: "Boa Gente",             tags: ["marca","mz"],               dif: "facil", nota: "" },
  { nome: "Taibo Bacar",           tags: ["marca","mz"],               dif: "facil", nota: "" },
  { nome: "Nivaldo",               tags: ["marca","mz"],               dif: "facil", nota: "" },
  { nome: "Deboneirs",             tags: ["marca","mz"],               dif: "facil", nota: "" },

  // ── TV / MEDIA MARCAS ─────────────────────────────────────
  { nome: "STV",                   tags: ["marca"],                    dif: "dificil", nota: "" },
  { nome: "TVM",                   tags: ["marca"],                    dif: "dificil", nota: "" },
  { nome: "Miramar",               tags: ["marca"],                    dif: "dificil", nota: "" },
  { nome: "TV Sucesso",            tags: ["marca"],                    dif: "dificil", nota: "" },
  { nome: "TV Record",             tags: ["marca"],                    dif: "dificil", nota: "" },
  { nome: "Globo",                 tags: ["marca"],                    dif: "dificil", nota: "" },
  { nome: "DStv",                  tags: ["marca"],                    dif: "dificil", nota: "" },
  { nome: "Zap",                   tags: ["marca"],                    dif: "dificil", nota: "" },
  { nome: "SIC",                   tags: ["marca"],                    dif: "dificil", nota: "" },
  { nome: "TVI",                   tags: ["marca"],                    dif: "dificil", nota: "" },

  // ── ANIME ─────────────────────────────────────────────────
  { nome: "Goku",                  tags: ["anime","personagem"],       dif: "facil",   nota: "" },
  { nome: "Naruto",                tags: ["anime","personagem"],       dif: "facil",   nota: "" },
  { nome: "Luffy",                 tags: ["anime","personagem"],       dif: "facil",   nota: "" },
  { nome: "Sasuke",                tags: ["anime","personagem"],       dif: "facil",   nota: "" },
  { nome: "Vegeta",                tags: ["anime","personagem"],       dif: "facil",   nota: "" },
  { nome: "Saitama",               tags: ["anime","personagem"],       dif: "facil",   nota: "" },
  { nome: "Gojo Satoru",           tags: ["anime","personagem"],       dif: "facil",   nota: "" },
  { nome: "Ash Ketchum",           tags: ["anime","personagem"],       dif: "facil",   nota: "" },
  { nome: "Itachi",                tags: ["anime","personagem"],       dif: "facil",   nota: "" },
  { nome: "Zoro",                  tags: ["anime","personagem"],       dif: "facil",   nota: "" },
  { nome: "Sailor Moon",           tags: ["anime","personagem"],       dif: "facil",   nota: "" },
  { nome: "Eren Jaeger",           tags: ["anime","personagem"],       dif: "facil",   nota: "" },
  { nome: "Levi",                  tags: ["anime","personagem"],       dif: "facil",   nota: "" },
  { nome: "Tanjiro",               tags: ["anime","personagem"],       dif: "facil",   nota: "" },
  { nome: "Nezuko",                tags: ["anime","personagem"],       dif: "facil",   nota: "" },
  { nome: "Light Yagami",          tags: ["anime","personagem"],       dif: "facil",   nota: "" },
  { nome: "L",                     tags: ["anime","personagem"],       dif: "facil",   nota: "" },
  { nome: "Deku",                  tags: ["anime","personagem"],       dif: "facil",   nota: "" },
  { nome: "Charizard",             tags: ["anime","personagem"],       dif: "facil",   nota: "" },
  { nome: "Gohan",                 tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Frieza",                tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Kakashi",               tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Sakura",                tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Madara",                tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Hinata",                tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Sanji",                 tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Nami",                  tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Ace",                   tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Shanks",                tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Ichigo",                tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Mikasa",                tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Armin",                 tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Zenitsu",               tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Inosuke",               tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Bakugo",                tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Todoroki",              tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "All Might",             tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Yuji Itadori",          tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Sukuna",                tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Ryuk",                  tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Edward Elric",          tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Killua",                tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Gon",                   tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Hisoka",                tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Genos",                 tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Kirito",                tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Asuna",                 tags: ["anime","personagem"],       dif: "medio",   nota: "" },
  { nome: "Piccolo",               tags: ["anime","personagem"],       dif: "dificil", nota: "" },
  { nome: "Cell",                  tags: ["anime","personagem"],       dif: "dificil", nota: "" },
  { nome: "Buu",                   tags: ["anime","personagem"],       dif: "dificil", nota: "" },
  { nome: "Byakuya",               tags: ["anime","personagem"],       dif: "dificil", nota: "" },
  { nome: "Aizen",                 tags: ["anime","personagem"],       dif: "dificil", nota: "" },
  { nome: "Whitebeard",            tags: ["anime","personagem"],       dif: "dificil", nota: "" },
  { nome: "Robin",                 tags: ["anime","personagem"],       dif: "dificil", nota: "" },
  { nome: "Rukia",                 tags: ["anime","personagem"],       dif: "dificil", nota: "" },
  { nome: "Lelouch",               tags: ["anime","personagem"],       dif: "dificil", nota: "" },
  { nome: "Spike Spiegel",         tags: ["anime","personagem"],       dif: "dificil", nota: "" },
  { nome: "Dragon Ball Z",         tags: ["anime"],                    dif: "dificil", nota: "" },
  { nome: "Naruto Shippuden",      tags: ["anime"],                    dif: "dificil", nota: "" },
  { nome: "One Piece",             tags: ["anime"],                    dif: "dificil", nota: "" },
  { nome: "Demon Slayer",          tags: ["anime"],                    dif: "dificil", nota: "" },
  { nome: "Attack on Titan",       tags: ["anime"],                    dif: "dificil", nota: "" },
  { nome: "Death Note",            tags: ["anime"],                    dif: "dificil", nota: "" },
  { nome: "Jujutsu Kaisen",        tags: ["anime"],                    dif: "dificil", nota: "" },

  // ── BÍBLIA ────────────────────────────────────────────────
  { nome: "Jesus",                 tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Maria",                 tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Moisés",                tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Noé",                   tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Adão",                  tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Eva",                   tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Davi",                  tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Golias",                tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Abraão",                tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "José",                  tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Sansão",                tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Dalila",                tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "João Batista",          tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Pedro",                 tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Paulo",                 tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Judas",                 tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Salomão",               tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Jonas",                 tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Daniel",                tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Maria Madalena",        tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Pilatos",               tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Herodes",               tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Lázaro",                tags: ["biblia"],                   dif: "facil",   nota: "" },
  { nome: "Isaque",                tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Jacó",                  tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Aarão",                 tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Josué",                 tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Saul",                  tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Elias",                 tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Eliseu",                tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Ester",                 tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Sara",                  tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Rute",                  tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Gideão",                tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Débora",                tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Rebeca",                tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Raquel",                tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "João",                  tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Lucas",                 tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Marcos",                tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Mateus",                tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "André",                 tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Tiago",                 tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Marta",                 tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Zaqueu",                tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Bate-Seba",             tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Isaías",                tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Jeremias",              tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Ezequiel",              tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Estêvão",               tags: ["biblia"],                   dif: "medio",   nota: "" },
  { nome: "Samuel",                tags: ["biblia"],                   dif: "dificil", nota: "" },
  { nome: "Boaz",                  tags: ["biblia"],                   dif: "dificil", nota: "" },
  { nome: "Jefté",                 tags: ["biblia"],                   dif: "dificil", nota: "" },
  { nome: "Abigail",               tags: ["biblia"],                   dif: "dificil", nota: "" },
  { nome: "Filipe",                tags: ["biblia"],                   dif: "dificil", nota: "" },
  { nome: "Bartolomeu",            tags: ["biblia"],                   dif: "dificil", nota: "" },
  { nome: "Nicodemos",             tags: ["biblia"],                   dif: "dificil", nota: "" },
  { nome: "Elisabete",             tags: ["biblia"],                   dif: "dificil", nota: "" },
  { nome: "Zacarias",              tags: ["biblia"],                   dif: "dificil", nota: "" },
  { nome: "Cornélio",              tags: ["biblia"],                   dif: "dificil", nota: "" },
  { nome: "Barnabé",               tags: ["biblia"],                   dif: "dificil", nota: "" },
  { nome: "Timóteo",               tags: ["biblia"],                   dif: "dificil", nota: "" },
  { nome: "Génesis",               tags: ["biblia","livro"],           dif: "dificil", nota: "" },
  { nome: "Êxodo",                 tags: ["biblia","livro"],           dif: "dificil", nota: "" },
  { nome: "Salmos",                tags: ["biblia","livro"],           dif: "dificil", nota: "" },
  { nome: "Provérbios",            tags: ["biblia","livro"],           dif: "dificil", nota: "" },
  { nome: "Apocalipse",            tags: ["biblia","livro"],           dif: "dificil", nota: "" },
];

// Categorias jogáveis — mantemos emoji/bg/shadow para a UI
export const CATEGORIAS = [
  { id: "mix",         nome: "Mix",         tag: "mix",        emoji: "🎲", bg: "linear-gradient(135deg,#7c5dfa,#5c4fd6)", shadow: "rgba(124,93,250,0.5)" },
  { id: "mz",          nome: "Moçambique",  tag: "mz",         emoji: "🇲🇿", bg: "linear-gradient(135deg,#16a34a,#15803d)", shadow: "rgba(22,163,74,0.5)" },
  { id: "global",      nome: "Global",      tag: "global",     emoji: "🌍", bg: "linear-gradient(135deg,#2563eb,#1d4ed8)", shadow: "rgba(37,99,235,0.5)" },
  { id: "cantores",    nome: "Cantores",    tag: "cantor",     emoji: "🎵", bg: "linear-gradient(135deg,#ea580c,#c2410c)", shadow: "rgba(234,88,12,0.5)" },
  { id: "desporto",    nome: "Desporto",    tag: "atleta",     emoji: "⚽", bg: "linear-gradient(135deg,#0891b2,#0e7490)", shadow: "rgba(8,145,178,0.5)" },
  { id: "animais",     nome: "Animais",     tag: "animal",     emoji: "🐾", bg: "linear-gradient(135deg,#d97706,#b45309)", shadow: "rgba(217,119,6,0.5)" },
  { id: "personagens", nome: "Personagens", tag: "personagem", emoji: "🦸", bg: "linear-gradient(135deg,#db2777,#be185d)", shadow: "rgba(219,39,119,0.5)" },
  { id: "comida",      nome: "Comida",      tag: "comida",     emoji: "🍕", bg: "linear-gradient(135deg,#dc2626,#b91c1c)", shadow: "rgba(220,38,38,0.5)" },
  { id: "marcas",      nome: "Marcas",      tag: "marca",      emoji: "🏷️", bg: "linear-gradient(135deg,#4f46e5,#4338ca)", shadow: "rgba(79,70,229,0.5)" },
  { id: "anime",       nome: "Anime",       tag: "anime",      emoji: "⛩️", bg: "linear-gradient(135deg,#ca8a04,#a16207)", shadow: "rgba(202,138,4,0.5)" },
  { id: "biblia",      nome: "Bíblia",      tag: "biblia",     emoji: "📖", bg: "linear-gradient(135deg,#92400e,#78350f)", shadow: "rgba(146,64,14,0.5)" },
];

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// Devolve o baralho de uma categoria, já embaralhado.
// soNomes=true → array de strings; soNomes=false → array de objectos completos.
export function getDeckForCategory(categoriaId, { soNomes = true } = {}) {
  let itens;
  if (categoriaId === "mix") {
    itens = QUEM_SOU_EU_DB.filter(i => i.tags.includes("mz") || i.tags.includes("global"));
  } else {
    const cat = CATEGORIAS.find(c => c.id === categoriaId);
    const tag = cat ? cat.tag : categoriaId;
    itens = QUEM_SOU_EU_DB.filter(i => i.tags.includes(tag));
  }
  const baralhado = shuffle(itens);
  return soNomes ? baralhado.map(i => i.nome) : baralhado;
}

export function getItems(tag, difs = ["facil","medio","dificil"]) {
  return QUEM_SOU_EU_DB.filter(i => i.tags.includes(tag) && difs.includes(i.dif));
}

export function getMix() {
  return QUEM_SOU_EU_DB.filter(i => i.tags.includes("mz") || i.tags.includes("global"));
}
